name: CI Pipeline

on:
  push:
    branches:
      - main  # Substitua pelo nome da branch que você deseja monitorar
  pull_request:
    branches:
      - main  # Substitua pelo nome da branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'  # Define a versão do .NET como 7.x

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with reporting
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
      
      - name: Publish Test Results
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: test-results
          path: '**/test_results.trx'
